heintzl/Kernbeisser-Gradle

- src/main/java/kernbeisser/CustomComponents/ShoppingTable/ShoppingCartModel.java
- src/main/java/kernbeisser/DBEntities/ShoppingItem.java
- src/main/java/kernbeisser/DBEntities/UserSettingValue.java
- src/main/java/kernbeisser/StartUp/DataImport/DataImportController.java
- src/main/java/kernbeisser/Useful/Tools.java
- src/main/java/kernbeisser/Windows/Pay/PayModel.java
> Julian dev

- src/main/java/kernbeisser/CustomComponents/FocusTraversal/FocusTraversal.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIView.form
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIView.java
> improved usability of shopping mask ui

- build.gradle
- src/main/java/kernbeisser/CustomComponents/ShoppingTable/ShoppingCartController.java
- src/main/java/kernbeisser/CustomComponents/ShoppingTable/ShoppingCartModel.java
- src/main/java/kernbeisser/DBEntities/ShoppingItem.java
- src/main/java/kernbeisser/Windows/Pay/PayController.java
- src/main/java/kernbeisser/Windows/Pay/PayModel.java
Hi!
Ich kann den Code leider aktuell nicht testen, da keine Artikel in meiner Datenbank sind (trotz Import).
Ich würde daher darum bitten, dass ihr erst schaut, ob weiterhin alles funktioniert wie bisher.
Zu Lombok schreibe ich woanders was.
> Order in shopping cart

- production/config.json
- src/main/java/kernbeisser/CustomComponents/ShoppingTable/ShoppingCartController.java
- src/main/java/kernbeisser/CustomComponents/ShoppingTable/ShoppingCartModel.java
- src/main/java/kernbeisser/DBEntities/ShoppingItem.java
- src/main/java/kernbeisser/Windows/Pay/PayModel.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIView.java
fix some problems with container deposit sorting, resolves #141
> Heintzl dev

- src/main/java/kernbeisser/DBEntities/SaleSession.java
- src/main/java/kernbeisser/DBEntities/User.java
- src/main/java/kernbeisser/Windows/CashierShoppingMask/CashierShoppingMaskController.java
- src/main/java/kernbeisser/Windows/CashierShoppingMask/CashierShoppingMaskView.form
- src/main/java/kernbeisser/Windows/CashierShoppingMask/CashierShoppingMaskView.java
- src/main/java/kernbeisser/Windows/EditUser/EditUserController.java
- src/main/java/kernbeisser/Windows/EditUser/EditUserModel.java
- src/main/java/kernbeisser/Windows/EditUser/EditUserView.form
- src/main/java/kernbeisser/Windows/EditUser/EditUserView.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIView.java
- src/main/java/kernbeisser/Windows/TabbedPanel/TabbedPaneController.java
- src/main/java/kernbeisser/Windows/View.java
Fixes #85
Es wurde die Möglichkeit hinzugefügt im Ladendienst Menu durch einen Doppelklick den zweit Ladendienst auszuwählen
> added second SaleSession seller

- src/main/java/kernbeisser/Config/ConfigManager.java
> use obfuscated password for db if none is given through config

- .gitignore
- production/config.json
- src/main/java/kernbeisser/Config/ConfigManager.java
- src/main/java/kernbeisser/DBEntities/Article.java
- src/main/java/kernbeisser/DBEntities/SettingValue.java
- src/main/java/kernbeisser/DBEntities/User.java
- src/main/java/kernbeisser/Windows/Menu/MenuView.form
- src/main/java/kernbeisser/Windows/Menu/MenuView.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ArticleSelector/ArticleSelectorController.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIController.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIView.java
- src/main/java/kernbeisser/Windows/Trasaction/TransactionController.java
- src/main/java/kernbeisser/Windows/Trasaction/TransactionView.form
- src/main/java/kernbeisser/Windows/Trasaction/TransactionView.java
part of #166 (see changes of 2020-07-18)
> Fixes part of #166

- src/main/java/kernbeisser/StartUp/DataImport/DataImportController.java
- src/main/resources/log4j2.properties
> Password salts during import

- src/main/java/kernbeisser/CustomComponents/ShoppingTable/ShoppingCartModel.java
- src/main/java/kernbeisser/CustomComponents/ShoppingTable/ShoppingCartView.form
- src/main/java/kernbeisser/DBEntities/SaleSession.java
- src/main/java/kernbeisser/Windows/CashierShoppingMask/CashierShoppingMaskController.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskModel.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIController.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIView.java
last dirty things to tackle #197
> refresh user info on reopening of tab

- src/main/java/kernbeisser/CustomComponents/FocusTraversal/FocusTraversal.java
- src/main/java/kernbeisser/Enums/ArticleType.java
- src/main/java/kernbeisser/Enums/Setting.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ArticleSelector/ArticleSelectorController.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ArticleSelector/ArticleSelectorView.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIController.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIView.java
Introduces a new enum 'ArticleType' to wrap and streamline the different cases of article type in the ShoppingMask. Two EnumSets are used for groups of article types which are often used together.
> Enum ArticleType

- src/main/java/kernbeisser/Windows/Setting/SettingController.java
- src/main/java/kernbeisser/Windows/Setting/SettingModel.java
- src/main/java/kernbeisser/Windows/Setting/SettingView.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIView.java
> Edit settings enum

- src/main/java/kernbeisser/CustomComponents/ShoppingTable/ShoppingCartController.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIController.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIView.form
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIView.java
> Fixes from ui review

- src/main/java/kernbeisser/CustomComponents/ObjectTable/ObjectTable.java
- src/main/java/kernbeisser/Windows/Menu/MenuView.form
- src/main/java/kernbeisser/Windows/Menu/MenuView.java
- src/main/java/kernbeisser/Windows/SynchronizeArticles/ArticleDifference.java
- src/main/java/kernbeisser/Windows/SynchronizeArticles/DifferenceType.java
- src/main/java/kernbeisser/Windows/SynchronizeArticles/SynchronizeArticleController.java
- src/main/java/kernbeisser/Windows/SynchronizeArticles/SynchronizeArticleModel.java
- src/main/java/kernbeisser/Windows/SynchronizeArticles/SynchronizeArticleView.form
- src/main/java/kernbeisser/Windows/SynchronizeArticles/SynchronizeArticleView.java
> Synchonise article view over work

- src/main/java/kernbeisser/DBEntities/Article.java
- src/main/java/kernbeisser/DBEntities/Permission.java
- src/main/java/kernbeisser/DBEntities/Shelf.java
- src/main/java/kernbeisser/DBEntities/User.java
- src/main/java/kernbeisser/Security/IterableProtection/CollectionProxy.java
- src/main/java/kernbeisser/Security/IterableProtection/MapProxy.java
- src/main/java/kernbeisser/Security/IterableProtection/ProtectedIterable.java
- src/main/java/kernbeisser/Security/IterableProtection/ProxyIterable.java
- src/main/java/kernbeisser/Security/IterableProtection/SetProxy.java
- src/main/java/kernbeisser/Security/PermissionSetSecurityHandler.java
- src/main/java/kernbeisser/Windows/SynchronizeArticles/SynchronizeArticleModel.java
cleaned up invoke function and added Annotation for collections maps
and sets to create a better understanding from what's happening
fixes #231
> added new annotation for iterables which should become protected

- reports/Bonrolle.jrxml
- reports/Kerni_Rechnung.jrxml
- src/main/java/kernbeisser/CustomComponents/KeyCapture.java
- src/main/java/kernbeisser/DBEntities/Purchase.java
- src/main/java/kernbeisser/DBEntities/ShoppingItem.java
- src/main/java/kernbeisser/Enums/PermissionKey.java
- src/main/java/kernbeisser/Enums/RawPrice.java
- src/main/java/kernbeisser/Enums/ShoppingItemSum.java
- src/main/java/kernbeisser/Reports/ReportManager.java
- src/main/java/kernbeisser/Security/PermissionSetSecurityHandler.java
- src/main/java/kernbeisser/Windows/Pay/PayController.java
- src/main/java/kernbeisser/Windows/Pay/PayModel.java
- src/main/java/kernbeisser/Windows/Pay/PayView.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIController.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIView.form
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIView.java
adds solidarity surcharge closes #248
> Solidarity surcharge

- src/main/java/kernbeisser/CustomComponents/SearchBox/SearchBoxView.java
- src/main/java/kernbeisser/DBEntities/Article.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ArticleSelector/ArticleSelectorController.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ArticleSelector/ArticleSelectorView.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIController.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIView.java
- src/main/java/kernbeisser/Windows/WindowImpl/SubWindow.java
fixes #225 
Die drei Punkte wurden abgearbeitet, beim barcode scannen konnte ich den Fehler auch nach 12 starten reproduzieren, ich denke mal das darauf schließen lässt das dieser Issue nicht mehr vorhanden ist.
> Barcode issue

- src/main/java/kernbeisser/CustomComponents/ObjectTable/Column.java
- src/main/java/kernbeisser/CustomComponents/ObjectTable/ObjectTable.java
- src/main/java/kernbeisser/CustomComponents/ObjectTable/StripedRenderer.java
- src/main/java/kernbeisser/Windows/EditUsers/EditUsers.java
> added Column.NUMBER_SORTER

- build.gradle
- production/config.json
- reports/Kerni_Rechnung.jrxml
- src/main/java/kernbeisser/Config/ConfigManager.java
- src/main/java/kernbeisser/Reports/ReportManager.java
Ich habe einige kleinere Fehler im Drucken unter Linux gefunden, aber nichts dramatisches.
Allerdings gab es eine Merkwürdigkeit im ReportsManager. Dort war ein anderer Key für die Config gefordert, als in der Config (meine und das Template) angegeben war.
Ich hab das korrigiert, aber ggf. müssen lokal falsche Konfigurationen angepasst werden.
Drucken über Default Printer hat einwandfrei geklappt.
> Linux printing

- src/main/java/kernbeisser/Enums/Setting.java
- src/main/java/kernbeisser/Useful/Tools.java
- src/main/java/kernbeisser/Windows/CashierShoppingMask/CashierShoppingMaskController.java
- src/main/java/kernbeisser/Windows/CashierShoppingMask/CashierShoppingMaskModel.java
- src/main/java/kernbeisser/Windows/CashierShoppingMask/CashierShoppingMaskView.java
- src/main/java/kernbeisser/Windows/ViewContainers/SubWindow.java
> Add accounting report to sale session

- src/main/java/kernbeisser/CustomComponents/Dialogs/LogInDialog.java
- src/main/java/kernbeisser/Enums/TransactionType.java
- src/main/java/kernbeisser/Windows/CashierShoppingMask/CashierShoppingMaskController.java
- src/main/java/kernbeisser/Windows/EditUserGroup/EditUserGroupController.java
- src/main/java/kernbeisser/Windows/EditUserGroup/EditUserGroupModel.java
- src/main/java/kernbeisser/Windows/EditUserGroup/EditUserGroupView.form
- src/main/java/kernbeisser/Windows/EditUserGroup/EditUserGroupView.java
- src/main/java/kernbeisser/Windows/LogIn/LogInModel.java
- src/main/java/kernbeisser/Windows/Menu/MenuView.java
- src/main/java/kernbeisser/Windows/SpecialPriceEditor/SpecialPriceEditorController.java
- src/main/java/kernbeisser/Windows/Trasaction/TransactionController.java
- src/main/java/kernbeisser/Windows/Trasaction/TransactionModel.java
> User group management

- src/main/java/kernbeisser/DBEntities/ArticleBase.java
- src/main/java/kernbeisser/DBEntities/Offer.java
- src/main/java/kernbeisser/DBEntities/ShoppingItem.java
- src/main/java/kernbeisser/DBEntities/SurchargeTable.java
- src/main/java/kernbeisser/Enums/Setting.java
- src/main/java/kernbeisser/StartUp/DataImport/DataImportView.java
- src/main/java/kernbeisser/Tasks/Catalog.java
offers from offer table are now taken into account for shopping item net price and naming
> Offer shopping

- src/main/java/kernbeisser/DBEntities/Article.java
- src/main/java/kernbeisser/DBEntities/ArticleBase.java
- src/main/java/kernbeisser/StartUp/DataImport/DataImportController.java
- src/main/java/kernbeisser/StartUp/DataImport/DataImportModel.java
- src/main/java/kernbeisser/Tasks/Articles.java
- src/main/java/kernbeisser/Windows/MVC/Controller.java
- src/main/java/kernbeisser/Windows/Menu/MenuView.form
- src/main/java/kernbeisser/Windows/Menu/MenuView.java
- src/main/java/kernbeisser/Windows/SpecialPriceEditor/SpecialPriceEditorController.java
- src/main/java/kernbeisser/Windows/SpecialPriceEditor/SpecialPriceEditorModel.java
- src/main/java/kernbeisser/Windows/SpecialPriceEditor/SpecialPriceEditorView.java
fixed data importing for offers
fixed ui for offer editing
removed collection offers in article
> fixed Offer Management

- src/main/java/kernbeisser/CustomComponents/AccessChecking/ObjectForm.java
- src/main/java/kernbeisser/CustomComponents/Dialogs/SelectionDialog.java
- src/main/java/kernbeisser/CustomComponents/ObjectTable/ObjectTable.java
- src/main/java/kernbeisser/CustomComponents/TextFields/FilterField.java
- src/main/java/kernbeisser/DBEntities/ArticleBase.java
- src/main/java/kernbeisser/DBEntities/ShoppingItem.java
- src/main/java/kernbeisser/Windows/Menu/MenuView.form
- src/main/java/kernbeisser/Windows/Menu/MenuView.java
- src/main/java/kernbeisser/Windows/SpecialPriceEditor/SpecialPriceEditorView.java
- src/main/java/kernbeisser/Windows/Supply/SupplyController.java
- src/main/java/kernbeisser/Windows/Supply/SupplyModel.java
- src/main/java/kernbeisser/Windows/Supply/SupplyView.form
- src/main/java/kernbeisser/Windows/Supply/SupplyView.java
> Add supply window

- production/config.json
- reports/.settings/org.eclipse.core.resources.prefs
- reports/BenutzerSchlüssel.jrxml
- reports/BuchhaltungBonUebersicht.jrxml
- reports/UserBalance.jrxml
- src/main/java/kernbeisser/DBEntities/Purchase.java
- src/main/java/kernbeisser/DBEntities/ShoppingItem.java
- src/main/java/kernbeisser/Reports/AccountingReport.java
- src/main/java/kernbeisser/Reports/KeyUserList.java
- src/main/java/kernbeisser/Windows/AccountingReports/AccountingReportsController.java
- src/main/java/kernbeisser/Windows/AccountingReports/AccountingReportsModel.java
- src/main/java/kernbeisser/Windows/AccountingReports/AccountingReportsView.form
- src/main/java/kernbeisser/Windows/AccountingReports/AccountingReportsView.java
- src/main/java/kernbeisser/Windows/CashierShoppingMask/CashierShoppingMaskModel.java
enhanced accounting report
added user key list for resolving ids to names
> More reports

- src/main/java/kernbeisser/Windows/Container/ContainerView.java
- src/main/java/kernbeisser/Windows/EditItems/EditItemsView.java
- src/main/java/kernbeisser/Windows/EditUserSetting/EditUserSettingView.java
- src/main/java/kernbeisser/Windows/Menu/MenuView.form
enhanced accounting report
added user key list for resolving ids to names
> fixed typos

- src/main/java/kernbeisser/DBEntities/CatalogDataSource.java
- src/main/resources/META-INF/persistence.xml
created object which holds all data supplied by the KornKraft catalog
> Catalog representation in database

- src/main/java/kernbeisser/CustomComponents/ObjectTable/ObjectTable.java
- src/main/java/kernbeisser/CustomComponents/SearchBox/SearchBoxController.java
- src/main/java/kernbeisser/CustomComponents/SearchBox/SearchBoxModel.java
- src/main/java/kernbeisser/CustomComponents/SearchBox/SearchBoxView.java
- src/main/java/kernbeisser/Windows/EditUserGroup/EditUserGroupController.java
- src/main/java/kernbeisser/Windows/ObjectView/ObjectViewController.java
- src/main/java/kernbeisser/Windows/Selector/SelectorController.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ArticleSelector/ArticleSelectorController.java
- src/main/java/kernbeisser/Windows/SpecialPriceEditor/SpecialPriceEditorController.java
- src/main/java/kernbeisser/Windows/SpecialPriceEditor/SpecialPriceEditorView.java
- src/main/java/kernbeisser/Windows/Trasaction/TransactionController.java
fixed addDoubleClickListener
removed setSelectedObject
> fixes #295

- reports/.settings/org.eclipse.core.resources.prefs
- reports/Etiketten.jrxml
- src/main/java/kernbeisser/DBEntities/ArticleBase.java
- src/main/java/kernbeisser/DBEntities/ShoppingItem.java
- src/main/java/kernbeisser/Reports/ArticleLabel.java
- src/main/java/kernbeisser/Useful/Date.java
> Article reports

- src/main/java/kernbeisser/DBEntities/Transaction.java
- src/main/java/kernbeisser/DBEntities/User.java
- src/main/java/kernbeisser/DBEntities/UserGroup.java
- src/main/java/kernbeisser/Reports/AccountingReport.java
- src/main/java/kernbeisser/StartUp/DataImport/DataImportModel.java
- src/main/java/kernbeisser/Windows/Trasaction/TransactionController.java
- src/main/java/kernbeisser/Windows/Trasaction/TransactionModel.java
- src/main/java/kernbeisser/Windows/Trasaction/TransactionView.java
- src/main/java/kernbeisser/Windows/UserInfo/UserInfoController.java
> renamed from to fromUser

- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIView.form
> increased size for shoppingItem Panel and shoppingCart Panel

- .idea/compiler.xml
- build.gradle
fixes compiling issue with older lombok version
> Lombok update required for idea 2020.3

- src/main/java/kernbeisser/DBEntities/Article.java
- src/main/java/kernbeisser/Tasks/Articles.java
- src/main/java/kernbeisser/Useful/Tools.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIController.java
custom article regression fix
added article property and tool for calculation of surchargeGroup values
> Fix custom article

- src/main/java/kernbeisser/CustomComponents/ObjectTable/Column.java
- src/main/java/kernbeisser/CustomComponents/ShoppingTable/ShoppingCartController.java
- src/main/java/kernbeisser/CustomComponents/ShoppingTable/ShoppingCartView.java
- src/main/java/kernbeisser/DBEntities/Article.java
- src/main/java/kernbeisser/DBEntities/ShoppingItem.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIController.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIView.java
fixed cart icons +/-/delete and other minor issues
> Fix shopping cart

- src/main/java/kernbeisser/DBEntities/Article.java
- src/main/java/kernbeisser/Enums/PermissionKey.java
- src/main/java/kernbeisser/Enums/Setting.java
- src/main/java/kernbeisser/Tasks/Articles.java
- src/main/java/kernbeisser/Windows/EditArticle/EditArticleView.form
- src/main/java/kernbeisser/Windows/EditArticle/EditArticleView.java
- src/main/java/kernbeisser/Windows/EditArticles/EditItemsController.java
- src/main/java/kernbeisser/Windows/EditArticles/EditItemsView.form
- src/main/java/kernbeisser/Windows/EditArticles/EditItemsView.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ArticleSelector/ArticleSelectorController.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ArticleSelector/ArticleSelectorView.form
- src/main/java/kernbeisser/Windows/ShoppingMask/ArticleSelector/ArticleSelectorView.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskModel.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIController.java
> Article shop range

- src/main/java/kernbeisser/CustomComponents/BarcodeCapture.java
- src/main/java/kernbeisser/Windows/MVC/Controller.java
I've added back tracing to process keyboard input, so that i don't have to implement a key capture for every sub controller.
Please review, so I don't destroy something :)
> add back tracing to process keyboard capture

- src/main/java/kernbeisser/CustomComponents/ObjectTable/Column.java
- src/main/java/kernbeisser/CustomComponents/ObjectTable/ObjectTable.java
- src/main/java/kernbeisser/Windows/LogIn/SimpleLogIn/SimpleLogInView.java
fixed glitches in Objecttable behaviour on Linux
> Fix linux UI

- src/main/java/kernbeisser/DBEntities/SurchargeGroup.java
- src/main/java/kernbeisser/Enums/UserSetting.java
- src/main/java/kernbeisser/Forms/ObjectForm/Components/DataListener.java
- src/main/java/kernbeisser/Windows/CashierShoppingMask/CashierShoppingMaskController.java
- src/main/java/kernbeisser/Windows/CashierShoppingMask/CashierShoppingMaskModel.java
- src/main/java/kernbeisser/Windows/CashierShoppingMask/CashierShoppingMaskView.java
- src/main/java/kernbeisser/Windows/EditSurchargeGroups/EditSurchargeGroupView.form
- src/main/java/kernbeisser/Windows/EditSurchargeGroups/EditSurchargeGroupView.java
- src/main/java/kernbeisser/Windows/EditUserSetting/EditUserSettingController.java
- src/main/java/kernbeisser/Windows/EditUserSetting/EditUserSettingModel.java
- src/main/java/kernbeisser/Windows/EditUserSetting/EditUserSettingView.form
- src/main/java/kernbeisser/Windows/EditUserSetting/EditUserSettingView.java
- src/main/java/kernbeisser/Windows/LogIn/SimpleLogIn/SimpleLogInController.java
> Fix issues

- src/main/java/kernbeisser/CustomComponents/ObjectTable/ObjectTable.java
- src/main/java/kernbeisser/CustomComponents/ShoppingTable/ShoppingCartController.java
- src/main/java/kernbeisser/CustomComponents/ShoppingTable/ShoppingCartView.java
- src/main/java/kernbeisser/Windows/CashierShoppingMask/CashierShoppingMaskView.form
- src/main/java/kernbeisser/Windows/CashierShoppingMask/CashierShoppingMaskView.java
- src/main/java/kernbeisser/Windows/LogIn/SimpleLogIn/SimpleLogInView.form
- src/main/java/kernbeisser/Windows/LogIn/SimpleLogIn/SimpleLogInView.java
- src/main/java/kernbeisser/Windows/Menu/MenuController.java
- src/main/java/kernbeisser/Windows/Menu/MenuView.form
- src/main/java/kernbeisser/Windows/Menu/MenuView.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIView.java
fix bugs, but no typos, found by P.B., fix serious transaction permission error
> Fixes from user feedback

- src/main/java/kernbeisser/CustomComponents/ObjectTable/ObjectTable.java
- src/main/java/kernbeisser/CustomComponents/ShoppingTable/ShoppingCartController.java
- src/main/java/kernbeisser/CustomComponents/ShoppingTable/ShoppingCartView.java
- src/main/java/kernbeisser/DBEntities/User.java
- src/main/java/kernbeisser/Enums/Setting.java
- src/main/java/kernbeisser/Reports/AccountingReport.java
- src/main/java/kernbeisser/StartUp/DataImport/DataImportModel.java
- src/main/java/kernbeisser/Useful/Users.java
- src/main/java/kernbeisser/Windows/LogIn/SimpleLogIn/SimpleLogInView.java
- src/main/java/kernbeisser/Windows/Menu/MenuController.java
- src/main/java/kernbeisser/Windows/Menu/MenuView.java
- src/main/java/kernbeisser/Windows/Trasaction/TransactionModel.java
- src/main/java/kernbeisser/Windows/UserInfo/UserInfoView.java
- src/main/resources/log4j2.xml
> Passoword Tokens

- src/main/java/kernbeisser/CustomComponents/ObjectTable/ObjectTable.java
- src/main/java/kernbeisser/Windows/Menu/MenuView.form
- src/main/java/kernbeisser/Windows/Menu/MenuView.java
- src/main/java/kernbeisser/Windows/PreOrder/PreOrderController.java
- src/main/java/kernbeisser/Windows/PreOrder/PreOrderModel.java
- src/main/java/kernbeisser/Windows/PreOrder/PreOrderView.java
added user preorder, fixes #250
> User preorder

- .idea/runConfigurations/Main_Proxy_.xml
- .idea/runConfigurations/Main_Unprotected_.xml
- src/main/java/kernbeisser/Config/Config.java
- src/main/java/kernbeisser/DBConnection/DBConnection.java
- src/main/java/kernbeisser/Main.java
- src/main/java/kernbeisser/Security/Access/Access.java
- src/main/java/kernbeisser/Windows/TabbedPane/TabViewContainer.java
- src/main/java/kernbeisser/Windows/ViewContainer.java
- src/main/java/kernbeisser/Windows/ViewContainers/JFrameWindow.java
- src/main/java/kernbeisser/Windows/ViewContainers/SubWindow.java
* added run configuration to git
* added agent enabled check in DBConnection static init
> Added run configuration to git

- src/main/java/kernbeisser/Forms/FormImplemetations/User/UserController.java
- src/main/java/kernbeisser/Forms/FormImplemetations/User/UserView.form
- src/main/java/kernbeisser/Forms/FormImplemetations/User/UserView.java
- src/main/java/kernbeisser/Forms/ObjectForm/Components/AccessCheckingField.java
> Various bugfixes

- src/main/java/kernbeisser/CustomComponents/ObjectTable/Column.java
- src/main/java/kernbeisser/CustomComponents/ObjectTable/ObjectTable.java
- src/main/java/kernbeisser/DBEntities/Job.java
- src/main/java/kernbeisser/DBEntities/User.java
- src/main/java/kernbeisser/Enums/PermissionKey.java
- src/main/java/kernbeisser/Forms/FormImplemetations/User/UserView.java
- src/main/java/kernbeisser/Windows/CollectionView/CollectionController.java
- src/main/java/kernbeisser/Windows/CollectionView/CollectionModel.java
- src/main/java/kernbeisser/Windows/CollectionView/CollectionView.form
- src/main/java/kernbeisser/Windows/CollectionView/CollectionView.java
- src/main/java/kernbeisser/Windows/PermissionAssignment/PermissionAssignmentController.java
- src/main/java/kernbeisser/Windows/PermissionAssignment/PermissionAssignmentModel.java
- src/main/java/kernbeisser/Windows/PermissionAssignment/PermissionAssignmentView.java
improved and fixed permission assignment
> Permission asssignment filter

- src/main/java/kernbeisser/Forms/ObjectForm/Components/AccessCheckingDatePicker.java
- src/main/java/kernbeisser/Security/PermissionSet.java
- src/main/java/kernbeisser/Unsafe/PermissionKeyMethodVisitor.java
- src/main/java/kernbeisser/Windows/ArticleOffersEditor/ArticleOffersEditorController.java
- src/main/java/kernbeisser/Windows/PreOrder/PreOrderController.java
+some weird stuff with the DateModel of our date picker
> Controller Button fixes

- src/main/java/kernbeisser/DBEntities/ShoppingItem.java
- src/main/java/kernbeisser/Windows/Pay/PayController.java
- src/main/java/kernbeisser/Windows/Pay/PayModel.java
- src/main/java/kernbeisser/Windows/Purchase/PurchaseController.java
> fixed #477

- src/main/java/kernbeisser/Forms/ObjectForm/Components/DataAnchor.java
fix bug with surcharge group window
> implement Predictable

- src/main/java/kernbeisser/CustomComponents/ObjectTable/Property.java
- src/main/java/kernbeisser/Windows/Supply/SupplySelector/SupplierFile.java
- src/main/java/kernbeisser/Windows/Supply/SupplyView.form
- src/main/java/kernbeisser/Windows/Supply/SupplyView.java
and fixed toString() of Property
> Added button to open SupplyView

- build.gradle
fixes jasper reports not running from fat jar
> merge jasperreports_extension.properties

- src/main/java/kernbeisser/CustomComponents/ComboBox/AdvancedComboBox.java
- src/main/java/kernbeisser/CustomComponents/ComboBox/AdvancedComboBoxKeySelectionManager.java
- src/main/java/kernbeisser/DBEntities/User.java
- src/main/java/kernbeisser/Enums/Setting.java
- src/main/java/kernbeisser/Enums/ShopRange.java
- src/main/java/kernbeisser/Forms/FormImplemetations/Article/ArticleController.java
- src/main/java/kernbeisser/Forms/FormImplemetations/Article/ArticleModel.java
- src/main/java/kernbeisser/Forms/FormImplemetations/Article/ArticleView.java
- src/main/java/kernbeisser/Windows/PreOrder/PreOrderView.java
-added alphabetic sorting to a few combo boxes
> -added search function to AdvancedComboBox

- src/main/java/kernbeisser/Windows/UserInfo/UserInfoController.java
- src/main/java/kernbeisser/Windows/UserInfo/UserInfoModel.java
> removed up counting column and use sql query instead

- src/main/java/kernbeisser/Enums/PermissionKey.java
- src/main/java/kernbeisser/Windows/Menu/MenuView.java
> Menu buttons

- src/main/java/kernbeisser/Enums/PermissionConstants.java
- src/main/java/kernbeisser/Security/Access/Access.java
- src/main/java/kernbeisser/Useful/Tools.java
fixes #583 
Es ist lange her ich weiß nicht ob die fixes überhaupt noch angebracht sind :)
> Fixed some access issues

- reports/Abhakplan.jrxml
- src/main/java/kernbeisser/DBEntities/Articles.java
- src/main/java/kernbeisser/DBEntities/PreOrder.java
- src/main/java/kernbeisser/DBEntities/User.java
- src/main/java/kernbeisser/Enums/Setting.java
- src/main/java/kernbeisser/Forms/FormImplemetations/Article/ArticleController.java
- src/main/java/kernbeisser/Reports/PreOrderChecklist.java
- src/main/java/kernbeisser/Windows/AccountingReports/AccountingReportsController.java
- src/main/java/kernbeisser/Windows/AccountingReports/AccountingReportsView.java
- src/main/java/kernbeisser/Windows/CashierShoppingMask/CashierShoppingMaskController.java
- src/main/java/kernbeisser/Windows/EditArticles/EditItemsController.java
- src/main/java/kernbeisser/Windows/PreOrder/PreOrderController.java
- src/main/java/kernbeisser/Windows/PreOrder/PreOrderModel.java
- src/main/java/kernbeisser/Windows/PreOrder/PreOrderView.form
- src/main/java/kernbeisser/Windows/PreOrder/PreOrderView.java
- src/main/java/kernbeisser/Windows/Trasaction/TransactionController.java
- src/main/java/kernbeisser/Windows/Trasaction/TransactionView.java
> Fixes from employee review

- reports/Abhakplan.jrxml
- src/main/java/kernbeisser/DBEntities/Article.java
- src/main/java/kernbeisser/DBEntities/Articles.java
- src/main/java/kernbeisser/DBEntities/ShoppingItem.java
- src/main/java/kernbeisser/DBEntities/User.java
- src/main/java/kernbeisser/Enums/MetricUnits.java
- src/main/java/kernbeisser/Reports/ArticleLabel.java
- src/main/java/kernbeisser/Reports/ReportDTO/PriceListReportArticle.java
- src/main/java/kernbeisser/Windows/CollectionView/CollectionController.java
- src/main/java/kernbeisser/Windows/CollectionView/CollectionModel.java
- src/main/java/kernbeisser/Windows/CollectionView/CollectionView.java
- src/main/java/kernbeisser/Windows/PrintLabels/PrintLabelsController.java
- src/main/java/kernbeisser/Windows/PrintLabels/PrintLabelsModel.java
- src/main/java/kernbeisser/Windows/PrintLabels/PrintLabelsView.java
- src/test/java/kernbeisser/DBEntities/ShoppingItemTest.java
ATTENTION: This pull fixes an auditing bug and requires manual database update to get rid of audited column on article. Please run this sql-script:
ALTER TABLE Article_AUD DROP COLUMN printPool;
ALTER TABLE Article DROP COLUMN printPool;
The column will be recreated by hibernate
> Multi lables

- src/main/java/kernbeisser/DBEntities/Articles.java
- src/main/java/kernbeisser/DBEntities/ShoppingItem.java
- src/main/java/kernbeisser/Windows/PreOrder/PreOrderController.java
- src/main/java/kernbeisser/Windows/PreOrder/PreOrderModel.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIController.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskUIView.java
> Transient shopping item

- build.gradle
- production/config.json
- src/main/java/kernbeisser/Windows/CashierShoppingMask/CashierShoppingMaskController.java
- src/main/java/kernbeisser/Windows/Menu/MenuController.java
- src/main/java/kernbeisser/Windows/Menu/MenuView.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskController.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskModel.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskView.form
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskView.java
- src/main/java/kernbeisser/Windows/SoloShoppingMask/SoloShoppingMaskController.java
- src/main/java/kernbeisser/Windows/SoloShoppingMask/SoloShoppingMaskView.form
- src/main/java/kernbeisser/Windows/SoloShoppingMask/SoloShoppingMaskView.java
- src/main/java/kernbeisser/Windows/Transaction/TransactionController.java
- src/main/java/kernbeisser/Windows/Transaction/TransactionModel.java
- src/main/java/kernbeisser/Windows/Transaction/TransactionView.form
- src/main/java/kernbeisser/Windows/Transaction/TransactionView.java
Some ugly named classes have been renamed. Most dependencies are up to date now. 
N.B.: No updates to hibernate, as with v. 5.6 no db-connection could be established!
**Breaking change:** database url must use "mariadb://"-protocol now, as "mysql://" is no longer supported!
> Refactoring and dependency updates

- src/main/java/kernbeisser/DBEntities/CatalogDataSource.java
- src/main/java/kernbeisser/Enums/PermissionKey.java
- src/main/java/kernbeisser/Exeptions/CatalogImportErrorException.java
- src/main/java/kernbeisser/Exeptions/CatalogImportWarningException.java
- src/main/java/kernbeisser/Exeptions/UnknownFileFormatException.java
- src/main/java/kernbeisser/Tasks/Catalog/BoolValues.java
- src/main/java/kernbeisser/Tasks/Catalog/Catalog.java
- src/main/java/kernbeisser/Tasks/Catalog/CatalogImportError.java
- src/main/java/kernbeisser/Tasks/Catalog/CatalogImporter.java
- src/main/java/kernbeisser/Tasks/Catalog/Merge/CatalogMergeSession.java
- src/main/java/kernbeisser/Useful/Date.java
- src/main/java/kernbeisser/Useful/Tools.java
- src/main/java/kernbeisser/VersionIntegrationTools/UpdatingTools/AddCatalogImportPermission.java
- src/main/java/kernbeisser/VersionIntegrationTools/Version.java
- src/main/java/kernbeisser/VersionIntegrationTools/VersionUpdatingTool.java
- src/main/java/kernbeisser/Windows/CatalogImport/CatalogImportController.java
- src/main/java/kernbeisser/Windows/CatalogImport/CatalogImportModel.java
- src/main/java/kernbeisser/Windows/CatalogImport/CatalogImportView.form
- src/main/java/kernbeisser/Windows/CatalogImport/CatalogImportView.java
- src/main/java/kernbeisser/Windows/LogIn/SimpleLogIn/SimpleLogInView.java
- src/main/java/kernbeisser/Windows/Menu/MenuView.form
- src/main/java/kernbeisser/Windows/Menu/MenuView.java
Kornkraft Katalog kann jetzt in die Datenbank eingelesen werden
> 685 kornkraft katalog einlesen

- src/main/java/kernbeisser/Forms/FormImplemetations/CatalogEntry/CatalogEntryView.form
- src/main/java/kernbeisser/Forms/FormImplemetations/CatalogEntry/CatalogEntryView.java
- src/main/java/kernbeisser/Forms/ObjectForm/ObjectForm.java
- src/main/java/kernbeisser/Tasks/Catalog/CatalogImporter.java
- src/main/java/kernbeisser/Windows/CatalogImport/CatalogImportController.java
- src/main/java/kernbeisser/Windows/CatalogImport/CatalogImportModel.java
- src/main/java/kernbeisser/Windows/PrintLabels/PrintLabelsController.java
- src/main/java/kernbeisser/Windows/PrintLabels/PrintLabelsModel.java
- src/main/java/kernbeisser/Windows/ShoppingMask/ShoppingMaskView.java
> 716 unbehandelte ausnahme beim einlesen des katalogheaders

- src/main/java/kernbeisser/Windows/PermissionAssignment/PermissionAssignmentController.java
- src/main/java/kernbeisser/Windows/PermissionManagement/PermissionController.java
add admin-role to PermissionController-UI
> remove obsolete code for cashier-grants, 

- app/src/main/java/kernbeisser/DBEntities/ShoppingItem.java
- app/src/main/java/kernbeisser/Reports/ReportDTO/PriceListReportArticle.java
- app/src/main/java/kernbeisser/Useful/Date.java
- app/src/main/java/kernbeisser/Windows/PreOrder/PreOrderView.java
- app/src/main/java/kernbeisser/Windows/Supply/SupplyController.java
- app/src/main/java/kernbeisser/Windows/Supply/SupplyModel.java
- app/src/main/java/kernbeisser/Windows/Supply/SupplySelector/LineContent.java
- app/src/main/java/kernbeisser/Windows/Supply/SupplySelector/SupplySelectorView.java
- app/src/main/java/kernbeisser/Windows/Supply/SupplyView.java
- reports/Etiketten.jrxml
A minor change in PreOrder and some fixes of unit display in Supply
> Fix preorder sorting

- app/src/main/java/kernbeisser/Windows/Menu/MenuView.form
- app/src/main/java/kernbeisser/Windows/Menu/MenuView.java
this is a no brainer - no review required
> fix permission key for supply button; remove obsolete buttons

- .gitignore
- reports/.settings/org.eclipse.core.resources.prefs
- reports/Etiketten.jrxml
Increased field size for container size by 1 px and changed text adjustment to font scaling
> insure that the whole content is printed

- app/src/main/java/kernbeisser/Reports/AccountingReport.java
- app/src/main/java/kernbeisser/Reports/Report.java
- app/src/main/java/kernbeisser/Windows/AccountingReports/AccountingReportsView.java
- app/src/main/java/kernbeisser/Windows/CashierShoppingMask/CashierShoppingMaskModel.java
removes some reasons for missing out accounting reports in the cloud folder (Email from accountant on July 15 '25)
> Assert accouting report creation

- app/src/main/java/kernbeisser/DBEntities/PreOrder.java
- app/src/main/java/kernbeisser/DBEntities/Repositories/TransactionRepository.java
- app/src/main/java/kernbeisser/DBEntities/Transaction.java
- app/src/main/java/kernbeisser/DBEntities/User.java
- app/src/main/java/kernbeisser/Exeptions/InvalidVATValueException.java
- app/src/main/java/kernbeisser/Reports/AccountingReport.java
- app/src/main/java/kernbeisser/Reports/PreOrderChecklist.java
- app/src/main/java/kernbeisser/Reports/ReportDTO/AccountingReportItem.java
- app/src/main/java/kernbeisser/Useful/Constants.java
- app/src/main/java/kernbeisser/Windows/AccountingReports/AccountingReportsController.java
- app/src/main/java/kernbeisser/Windows/AccountingReports/AccountingReportsView.java
- app/src/main/java/kernbeisser/Windows/CashierShoppingMask/CashierShoppingMaskModel.java
- app/src/main/java/kernbeisser/Windows/PreOrder/PreOrderModel.java
- app/src/test/java/kernbeisser/Reports/AccountingReportTest.java
- reports/BuchhaltungUmsaetze.jrxml
fix bug where shop_user was mistaken for customer in accounting report
> 839 historic sums for historic accountingreports
